Repository jberkers42/tenable-tools, pull requests merged in 2022-03, with the labels that each got.

#1 ResponseHeadersVariable requires Powershell 7.0
  src/Tenable.Tools.psd1
Labels: bug

#3 v0.0.2 release preparation
  .github/linters/.powershell-psscriptanalyzer.psd1
  CHANGELOG.md
  Tenable.Tools.Build.ps1
  src/Tenable.Tools.psd1
Labels: enhancement

#4 v0.0.2 Release
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Enhancement.md
  .github/PULL_REQUEST_TEMPLATE/Pull_request.md
  .github/linters/.markdownlint.json
  .github/linters/.powershell-psscriptanalyzer.psd1
  .github/workflows/mega-linter.yml
  .gitlab-ci.yml
  CHANGELOG.md
  Tenable.Tools.Build.ps1
  examples/logrhythm/Invoke-TioLrCategorySync.md
  examples/logrhythm/Invoke-TioLrCategorySync.ps1
  src/Tenable.Tools.psd1
  src/docs/en-US/Get-TioAsset.md
  src/docs/en-US/Get-TioExportAsset.md
  src/docs/en-US/Get-TioExportAssetChunk.md
  src/docs/en-US/Get-TioExportAssetStatus.md
  src/docs/en-US/Get-TioFolder.md
  src/docs/en-US/Get-TioMsspAccount.md
  src/docs/en-US/Get-TioMsspLogo.md
  src/docs/en-US/Get-TioTagCategory.md
  src/docs/en-US/Get-TioTagValue.md
  src/docs/en-US/New-TioCredential.md
  src/docs/en-US/Set-TioMsspLogo.md
  src/public/general/New-TioCredential.ps1
  src/public/mssp/Get-TioMsspAccount.ps1
  src/public/mssp/Get-TioMsspLogo.ps1
  src/public/mssp/Set-TioMsspLogo.ps1
  tests/public/Get-TioMsspAccount.Tests.ps1
  tests/public/Get-TioMsspLogo.Tests.ps1
  tests/public/New-TioCredential.Tests.ps1
  tests/public/data/Get-TioMsspAccount.json
  tests/public/data/Get-TioMsspLogo-uuid.json
  tests/public/data/Get-TioMsspLogo.json
Labels: bug, documentation, enhancement
